//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 26/11/2014 10:46:06 p.m.
namespace DAO
{
    
    /// <summary>
    /// There are no comments for NuestraTierraEntities in the schema.
    /// </summary>
    public partial class NuestraTierraEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new NuestraTierraEntities object using the connection string found in the 'NuestraTierraEntities' section of the application configuration file.
        /// </summary>
        public NuestraTierraEntities() : 
                base("name=NuestraTierraEntities", "NuestraTierraEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new NuestraTierraEntities object.
        /// </summary>
        public NuestraTierraEntities(string connectionString) : 
                base(connectionString, "NuestraTierraEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new NuestraTierraEntities object.
        /// </summary>
        public NuestraTierraEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "NuestraTierraEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Chat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Chat> Chat
        {
            get
            {
                if ((this._Chat == null))
                {
                    this._Chat = base.CreateQuery<Chat>("[Chat]");
                }
                return this._Chat;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Chat> _Chat;
        /// <summary>
        /// There are no comments for Padres in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Padres> Padres
        {
            get
            {
                if ((this._Padres == null))
                {
                    this._Padres = base.CreateQuery<Padres>("[Padres]");
                }
                return this._Padres;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Padres> _Padres;
        /// <summary>
        /// There are no comments for Chat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToChat(Chat chat)
        {
            base.AddObject("Chat", chat);
        }
        /// <summary>
        /// There are no comments for Padres in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPadres(Padres padres)
        {
            base.AddObject("Padres", padres);
        }
    }
    /// <summary>
    /// There are no comments for NuestraTierraModel.Chat in the schema.
    /// </summary>
    /// <KeyProperties>
    /// idChat
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NuestraTierraModel", Name="Chat")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Chat : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Chat object.
        /// </summary>
        /// <param name="idChat">Initial value of idChat.</param>
        /// <param name="nombrePadre">Initial value of NombrePadre.</param>
        /// <param name="texto">Initial value of Texto.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Chat CreateChat(int idChat, string nombrePadre, string texto)
        {
            Chat chat = new Chat();
            chat.idChat = idChat;
            chat.NombrePadre = nombrePadre;
            chat.Texto = texto;
            return chat;
        }
        /// <summary>
        /// There are no comments for property idChat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int idChat
        {
            get
            {
                return this._idChat;
            }
            set
            {
                this.OnidChatChanging(value);
                this.ReportPropertyChanging("idChat");
                this._idChat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("idChat");
                this.OnidChatChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _idChat;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChatChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnidChatChanged();
        /// <summary>
        /// There are no comments for property NombrePadre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NombrePadre
        {
            get
            {
                return this._NombrePadre;
            }
            set
            {
                this.OnNombrePadreChanging(value);
                this.ReportPropertyChanging("NombrePadre");
                this._NombrePadre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NombrePadre");
                this.OnNombrePadreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NombrePadre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombrePadreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombrePadreChanged();
        /// <summary>
        /// There are no comments for property Texto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Texto
        {
            get
            {
                return this._Texto;
            }
            set
            {
                this.OnTextoChanging(value);
                this.ReportPropertyChanging("Texto");
                this._Texto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Texto");
                this.OnTextoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Texto;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTextoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTextoChanged();
    }
    /// <summary>
    /// There are no comments for NuestraTierraModel.Padres in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Mail
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NuestraTierraModel", Name="Padres")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Padres : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Padres object.
        /// </summary>
        /// <param name="mail">Initial value of Mail.</param>
        /// <param name="nombre">Initial value of Nombre.</param>
        /// <param name="admin">Initial value of Admin.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Padres CreatePadres(string mail, string nombre, bool admin)
        {
            Padres padres = new Padres();
            padres.Mail = mail;
            padres.Nombre = nombre;
            padres.Admin = admin;
            return padres;
        }
        /// <summary>
        /// There are no comments for property Mail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Mail
        {
            get
            {
                return this._Mail;
            }
            set
            {
                this.OnMailChanging(value);
                this.ReportPropertyChanging("Mail");
                this._Mail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Mail");
                this.OnMailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Mail;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMailChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnMailChanged();
        /// <summary>
        /// There are no comments for property Nombre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Password;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPasswordChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for property Admin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool Admin
        {
            get
            {
                return this._Admin;
            }
            set
            {
                this.OnAdminChanging(value);
                this.ReportPropertyChanging("Admin");
                this._Admin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Admin");
                this.OnAdminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _Admin;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAdminChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAdminChanged();
        /// <summary>
        /// There are no comments for property Confirmado in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> Confirmado
        {
            get
            {
                return this._Confirmado;
            }
            set
            {
                this.OnConfirmadoChanging(value);
                this.ReportPropertyChanging("Confirmado");
                this._Confirmado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Confirmado");
                this.OnConfirmadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _Confirmado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConfirmadoChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConfirmadoChanged();
    }
}
